package calcu_vectores;

import java.awt.Color;
import java.text.DecimalFormat;

public class Interfaz extends javax.swing.JFrame {

    Operaciones2D oper = new Operaciones2D();
    DecimalFormat formato1 = new DecimalFormat("#.000");
    Double grafX, grafY, grafZ;
    double arrX[];
    double arrY[];
    double arrZ[];
    public double []x = {0.0,0.0};
    public double []y = {0.0,0.0};
    public double []z = {0.0,0.0};
    public Interfaz() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabedVectores = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMagnitud = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMagnitud2D = new javax.swing.JTextPane();
        lblMagnitud1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComponenteA2D = new javax.swing.JTextPane();
        lblComponenteA = new javax.swing.JLabel();
        lblComponenteB = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComponenteB2D = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAngulo2D = new javax.swing.JTextPane();
        lblAngulo2d = new javax.swing.JLabel();
        btnCalcular2D = new javax.swing.JButton();
        btnGraficar2D = new javax.swing.JToggleButton();
        btnLimpiar2D = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnSumaVec2D = new javax.swing.JButton();
        btnProductoPunto2D = new javax.swing.JButton();
        btnRestaVec2D = new javax.swing.JButton();
        btnEcuacionLineaRecta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlVector3D = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMagnitud3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtMagnitud3D = new javax.swing.JTextPane();
        lblMagnitud4 = new javax.swing.JLabel();
        lblComponenteA1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtComponenteA3D = new javax.swing.JTextPane();
        lblComponenteB1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtComponenteB3D = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtComponenteC3D = new javax.swing.JTextPane();
        lblComponenteB2 = new javax.swing.JLabel();
        lblAngulo2d1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAngulo3D = new javax.swing.JTextPane();
        btnCalcular3D = new javax.swing.JButton();
        btnGraficar3D = new javax.swing.JToggleButton();
        btnLimpiar3D = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnSumaVec3D1 = new javax.swing.JButton();
        btnProductoPunto3D1 = new javax.swing.JButton();
        btnProductoCruz3D1 = new javax.swing.JButton();
        btnRestaVec3D = new javax.swing.JButton();
        btnEcuacionPlano = new javax.swing.JButton();
        btnEscalar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalcVectores");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CALCULADORA DE VECTORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabedVectores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("VECTORES 2D");

        lblMagnitud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud.setText("Magnitud");

        jScrollPane1.setViewportView(txtMagnitud2D);

        lblMagnitud1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud1.setText("Compontes");

        jScrollPane2.setViewportView(txtComponenteA2D);

        lblComponenteA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteA.setText("A");

        lblComponenteB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB.setText("B");

        jScrollPane3.setViewportView(txtComponenteB2D);

        jScrollPane4.setViewportView(txtAngulo2D);

        lblAngulo2d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngulo2d.setText("Angulo");

        btnCalcular2D.setText("CALCULAR");
        btnCalcular2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular2DActionPerformed(evt);
            }
        });

        btnGraficar2D.setText("GRÁFICAR");
        btnGraficar2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficar2DActionPerformed(evt);
            }
        });

        btnLimpiar2D.setText("LIMPIAR");
        btnLimpiar2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar2DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCalcular2D)
                        .addGap(18, 18, 18)
                        .addComponent(btnGraficar2D)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar2D)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1)
                            .addComponent(lblMagnitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lblMagnitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(lblAngulo2d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblComponenteA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lblComponenteB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                        .addGap(153, 153, 153))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMagnitud1)
                            .addComponent(lblAngulo2d))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteA)
                            .addComponent(lblComponenteB)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMagnitud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular2D)
                    .addComponent(btnGraficar2D)
                    .addComponent(btnLimpiar2D))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSumaVec2D.setText("SUMA VECTORES");
        btnSumaVec2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaVec2DActionPerformed(evt);
            }
        });

        btnProductoPunto2D.setText("PRODUCTO PUNTO");
        btnProductoPunto2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoPunto2DActionPerformed(evt);
            }
        });

        btnRestaVec2D.setText("RESTA VECTORES");
        btnRestaVec2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaVec2DActionPerformed(evt);
            }
        });

        btnEcuacionLineaRecta.setText("ECUACION LINEA RECTA");
        btnEcuacionLineaRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcuacionLineaRectaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnSumaVec2D)
                .addGap(12, 12, 12)
                .addComponent(btnRestaVec2D)
                .addGap(18, 18, 18)
                .addComponent(btnProductoPunto2D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEcuacionLineaRecta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumaVec2D)
                    .addComponent(btnProductoPunto2D)
                    .addComponent(btnRestaVec2D)
                    .addComponent(btnEcuacionLineaRecta))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabedVectores.addTab("2D", jPanel3);

        jLabel3.setText("VECTORES 3D");

        lblMagnitud3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud3.setText("Magnitud");

        txtMagnitud3D.setEditable(false);
        jScrollPane6.setViewportView(txtMagnitud3D);

        lblMagnitud4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud4.setText("Compontes");

        lblComponenteA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteA1.setText("A");

        jScrollPane7.setViewportView(txtComponenteA3D);

        lblComponenteB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB1.setText("B");

        jScrollPane8.setViewportView(txtComponenteB3D);

        jScrollPane9.setViewportView(txtComponenteC3D);

        lblComponenteB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB2.setText("C");

        lblAngulo2d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngulo2d1.setText("Angulo");

        txtAngulo3D.setEditable(false);
        jScrollPane5.setViewportView(txtAngulo3D);

        btnCalcular3D.setText("CALCULAR");
        btnCalcular3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular3DActionPerformed(evt);
            }
        });

        btnGraficar3D.setText("GRÁFICAR");
        btnGraficar3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficar3DActionPerformed(evt);
            }
        });

        btnLimpiar3D.setText("LIMPIAR");
        btnLimpiar3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar3DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnCalcular3D)
                        .addGap(28, 28, 28)
                        .addComponent(btnGraficar3D)
                        .addGap(31, 31, 31)
                        .addComponent(btnLimpiar3D)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6)
                                    .addComponent(lblMagnitud3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(lblComponenteA1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(lblComponenteB1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblMagnitud4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblComponenteB2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAngulo2d1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5))))
                        .addGap(33, 33, 33))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblMagnitud4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteA1)
                            .addComponent(lblComponenteB1)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteB2)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMagnitud3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblAngulo2d1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular3D)
                    .addComponent(btnGraficar3D)
                    .addComponent(btnLimpiar3D))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVector3DLayout = new javax.swing.GroupLayout(pnlVector3D);
        pnlVector3D.setLayout(pnlVector3DLayout);
        pnlVector3DLayout.setHorizontalGroup(
            pnlVector3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVector3DLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlVector3DLayout.setVerticalGroup(
            pnlVector3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSumaVec3D1.setText("SUMA VECTORES");
        btnSumaVec3D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaVec3D1ActionPerformed(evt);
            }
        });

        btnProductoPunto3D1.setText("PRODUCTO PUNTO");
        btnProductoPunto3D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoPunto3D1ActionPerformed(evt);
            }
        });

        btnProductoCruz3D1.setText("PRODUCTO CRUZ");
        btnProductoCruz3D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoCruz3D1ActionPerformed(evt);
            }
        });

        btnRestaVec3D.setText("RESTA VECTORES");
        btnRestaVec3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaVec3DActionPerformed(evt);
            }
        });

        btnEcuacionPlano.setText("ECUACION DEL PLANO");
        btnEcuacionPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcuacionPlanoActionPerformed(evt);
            }
        });

        btnEscalar.setText("VECTOR POR ESCALAR");
        btnEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnEcuacionPlano))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSumaVec3D1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestaVec3D)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnProductoPunto3D1)
                        .addGap(18, 18, 18)
                        .addComponent(btnProductoCruz3D1)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEscalar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumaVec3D1)
                    .addComponent(btnProductoPunto3D1)
                    .addComponent(btnProductoCruz3D1)
                    .addComponent(btnRestaVec3D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEcuacionPlano)
                    .addComponent(btnEscalar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVector3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlVector3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabedVectores.addTab("3D", jPanel2);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabedVectores)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabedVectores, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcular2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular2DActionPerformed
       
        
        if(txtComponenteA2D.getText().length()==0 && txtComponenteB2D.getText().length()==0 ){
            //Solo con magnitud
            Double angulo= Double.parseDouble(txtAngulo2D.getText());
            Double magnitud= Double.parseDouble(txtMagnitud2D.getText());
            txtComponenteA2D.setText(formato1.format(oper.componenteA(magnitud, angulo)));
            txtComponenteB2D.setText(formato1.format(oper.componenteB(magnitud, angulo)));
        }
        else if(txtMagnitud2D.getText().length()==0  && txtAngulo2D.getText().length()==0 ){
            //Con componentes
            Double a= Double.parseDouble(txtComponenteA2D.getText());
            Double b= Double.parseDouble(txtComponenteB2D.getText());
            txtMagnitud2D.setText(formato1.format(oper.calcularMagnitud2D(a, b)));
            txtAngulo2D.setText(formato1.format(oper.calcularAngulo(a, b)));
            
        }
    }//GEN-LAST:event_btnCalcular2DActionPerformed

    private void btnLimpiar2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2DActionPerformed
        txtMagnitud2D.setText("");
        txtComponenteA2D.setText("");
        txtComponenteB2D.setText("");
         txtAngulo2D.setText("");
    }//GEN-LAST:event_btnLimpiar2DActionPerformed

    private void btnProductoPunto2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoPunto2DActionPerformed
        ProductoPunto2D pp2D= new ProductoPunto2D();
        pp2D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductoPunto2DActionPerformed

    private void btnLimpiar3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar3DActionPerformed
        txtMagnitud3D.setText("");
        txtComponenteA3D.setText("");
        txtComponenteB3D.setText("");
        txtComponenteC3D.setText("");
        txtAngulo3D.setText("");
    }//GEN-LAST:event_btnLimpiar3DActionPerformed

    private void btnCalcular3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular3DActionPerformed
        if(txtMagnitud3D.getText().length()==0  && txtAngulo3D.getText().length()==0 ){
            Double a= Double.parseDouble(txtComponenteA3D.getText());
            Double b= Double.parseDouble(txtComponenteB3D.getText());
            Double c= Double.parseDouble(txtComponenteC3D.getText());
            txtMagnitud3D.setText(formato1.format(oper.calcularMagnitud3D(a, b, c)));
            txtAngulo3D.setText(formato1.format(oper.calcularAngulo(c, oper.calcularMagnitud2D(a, b))));

        }
    }//GEN-LAST:event_btnCalcular3DActionPerformed

    private void btnProductoPunto3D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoPunto3D1ActionPerformed
        ProductoPunto3D pp3D = new ProductoPunto3D();
        pp3D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductoPunto3D1ActionPerformed

    private void btnProductoCruz3D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoCruz3D1ActionPerformed
        ProductoCruz3D pc3D = new ProductoCruz3D();
        pc3D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductoCruz3D1ActionPerformed

    private void btnGraficar2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficar2DActionPerformed
        grafX= Double.parseDouble(txtComponenteA2D.getText());
        grafY= Double.parseDouble(txtComponenteB2D.getText());
        
        arrX= hacerArreglo(x, grafX).clone();
        arrY=hacerArreglo(y, grafY).clone();
         //IMPRIME LOS VALORES DE 
        /*for(int i=0; i<arrX.length;i++){
            System.out.print(arrX[i]+" ");
        }
        for(int i=0; i<arrY.length;i++){
            System.out.print(arrY[i]+" ");
        }*/
        Grafica2D graf = new Grafica2D();
        graf.plot.addLinePlot("Vector Resultante",Color.BLUE,arrX,arrY);
        graf.espaGrafica.setVisible(true);
    }//GEN-LAST:event_btnGraficar2DActionPerformed

    private void btnSumaVec2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaVec2DActionPerformed
       SumaVectores2D sumVec = new SumaVectores2D();
       sumVec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSumaVec2DActionPerformed

    private void btnSumaVec3D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaVec3D1ActionPerformed
       SumaVectores3D sumVec = new SumaVectores3D();
       sumVec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSumaVec3D1ActionPerformed

    private void btnRestaVec3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaVec3DActionPerformed
       RestaVectores3D resVec = new RestaVectores3D();
       resVec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnRestaVec3DActionPerformed

    private void btnRestaVec2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaVec2DActionPerformed
       RestaVectores2D resVec = new RestaVectores2D();
       resVec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnRestaVec2DActionPerformed

    private void btnEcuacionLineaRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcuacionLineaRectaActionPerformed
        EcuacionLineaRecta lin = new EcuacionLineaRecta();
        lin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcuacionLineaRectaActionPerformed

    private void btnEcuacionPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcuacionPlanoActionPerformed
        EcuacionPlano plan = new EcuacionPlano();
        plan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcuacionPlanoActionPerformed

    private void btnGraficar3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficar3DActionPerformed
        //Obtener componentes
        grafX=Double.parseDouble(txtComponenteA3D.getText());
        grafY=Double.parseDouble(txtComponenteB3D.getText());
        grafZ=Double.parseDouble(txtComponenteC3D.getText());
        //Crear arreglos a graficar
        arrX= hacerArreglo(x, grafX).clone();
        arrY=hacerArreglo(y, grafY).clone();
        arrZ=hacerArreglo(z, grafZ).clone();
        
        /*System.out.print("Array X ");
        for(int i=0; i<arrX.length;i++){
            System.out.print(arrX[i]+" ");
        }
        System.out.print("Array Y ");
        for(int i=0; i<arrY.length;i++){
            System.out.print(arrY[i]+" ");
        }
        System.out.print("Array Z ");
        for(int i=0; i<arrZ.length;i++){
            System.out.print(arrZ[i]+" ");
        }*/
        
        Grafica3D graf = new Grafica3D();
        graf.grafica3D.addLinePlot("Vector Resultante", Color.BLUE, arrX, arrY, arrZ);
    }//GEN-LAST:event_btnGraficar3DActionPerformed

    private void btnEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalarActionPerformed
        Escalar2D esc = new Escalar2D();
        esc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnEscalarActionPerformed

    
    public double[] hacerArreglo(double[]arr, double valor){
        double []newA = new double[arr.length];
        
        for(int i=0; i<arr.length;i++){
            newA[i]=arr[i];
        }
        newA[newA.length-1] = valor;
        
        return newA;
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular2D;
    private javax.swing.JButton btnCalcular3D;
    private javax.swing.JButton btnEcuacionLineaRecta;
    private javax.swing.JButton btnEcuacionPlano;
    private javax.swing.JButton btnEscalar;
    private javax.swing.JToggleButton btnGraficar2D;
    private javax.swing.JToggleButton btnGraficar3D;
    private javax.swing.JButton btnLimpiar2D;
    private javax.swing.JButton btnLimpiar3D;
    private javax.swing.JButton btnProductoCruz3D1;
    private javax.swing.JButton btnProductoPunto2D;
    private javax.swing.JButton btnProductoPunto3D1;
    private javax.swing.JButton btnRestaVec2D;
    private javax.swing.JButton btnRestaVec3D;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSumaVec2D;
    private javax.swing.JButton btnSumaVec3D1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAngulo2d;
    private javax.swing.JLabel lblAngulo2d1;
    private javax.swing.JLabel lblComponenteA;
    private javax.swing.JLabel lblComponenteA1;
    private javax.swing.JLabel lblComponenteB;
    private javax.swing.JLabel lblComponenteB1;
    private javax.swing.JLabel lblComponenteB2;
    private javax.swing.JLabel lblMagnitud;
    private javax.swing.JLabel lblMagnitud1;
    private javax.swing.JLabel lblMagnitud3;
    private javax.swing.JLabel lblMagnitud4;
    private javax.swing.JPanel pnlVector3D;
    private javax.swing.JTabbedPane tabedVectores;
    private javax.swing.JTextPane txtAngulo2D;
    private javax.swing.JTextPane txtAngulo3D;
    private javax.swing.JTextPane txtComponenteA2D;
    private javax.swing.JTextPane txtComponenteA3D;
    private javax.swing.JTextPane txtComponenteB2D;
    private javax.swing.JTextPane txtComponenteB3D;
    private javax.swing.JTextPane txtComponenteC3D;
    private javax.swing.JTextPane txtMagnitud2D;
    private javax.swing.JTextPane txtMagnitud3D;
    // End of variables declaration//GEN-END:variables
}
