
package calcu_vectores;

import java.awt.Color;
import java.text.DecimalFormat;

public class ProductoCruz3D extends javax.swing.JFrame {
    
        DecimalFormat formato1 = new DecimalFormat("#.000");
        Operaciones2D oper = new Operaciones2D();
        
        Double grafX1, grafY1,grafZ1, grafX2, grafY2,grafZ2,grafRX,grafRY, grafRZ ;
        double arrX1[];
        double arrY1[];
        double arrZ1[];
        double arrX2[];
        double arrY2[];
        double arrZ2[];
        double arrRX[];
        double arrRY[];
        double arrRZ[];
        public double []x = {0.0,0.0};
        public double []y = {0.0,0.0};
        public double []z = {0.0,0.0};
        
    public ProductoCruz3D() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMagnitud = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMagnitud1 = new javax.swing.JTextPane();
        lblMagnitud1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComponenteA1 = new javax.swing.JTextPane();
        lblComponenteA = new javax.swing.JLabel();
        lblComponenteB = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComponenteB1 = new javax.swing.JTextPane();
        btnCalcular = new javax.swing.JButton();
        btnGraficar = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JButton();
        lblMagnitud2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMagnitud2 = new javax.swing.JTextPane();
        lblComponenteA1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtComponenteA2 = new javax.swing.JTextPane();
        lblMagnitud3 = new javax.swing.JLabel();
        lblComponenteB1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtComponenteB2 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtAngulo = new javax.swing.JTextPane();
        lblAngulo2d1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextPane();
        lblComponenteB2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComponenteC1 = new javax.swing.JTextPane();
        lblComponenteB3 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtComponenteC2 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        lblComponenteA2 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtResultA = new javax.swing.JTextPane();
        lblComponenteB4 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtResultB = new javax.swing.JTextPane();
        lblComponenteB5 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtResultC = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PRODUCTO CRUZ 3D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("VECTOR 1");

        lblMagnitud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud.setText("Magnitud");

        txtMagnitud1.setEditable(false);
        jScrollPane1.setViewportView(txtMagnitud1);

        lblMagnitud1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud1.setText("Compontes");

        jScrollPane2.setViewportView(txtComponenteA1);

        lblComponenteA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteA.setText("A");

        lblComponenteB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB.setText("B");

        jScrollPane3.setViewportView(txtComponenteB1);

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnGraficar.setText("GRÁFICAR");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblMagnitud2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud2.setText("Magnitud");

        txtMagnitud2.setEditable(false);
        jScrollPane5.setViewportView(txtMagnitud2);

        lblComponenteA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteA1.setText("A");

        jScrollPane6.setViewportView(txtComponenteA2);

        lblMagnitud3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud3.setText("Compontes");

        lblComponenteB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB1.setText("B");

        jScrollPane7.setViewportView(txtComponenteB2);

        txtAngulo.setEditable(false);
        jScrollPane8.setViewportView(txtAngulo);

        lblAngulo2d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngulo2d1.setText("Angulo");

        jLabel3.setText("VECTOR 2");

        jLabel4.setText("RESULTADO VECTOR");

        txtResult.setEditable(false);
        jScrollPane9.setViewportView(txtResult);

        lblComponenteB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB2.setText("C");

        jScrollPane4.setViewportView(txtComponenteC1);

        lblComponenteB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB3.setText("C");

        jScrollPane10.setViewportView(txtComponenteC2);

        jLabel5.setText("COMPONENTES");

        lblComponenteA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteA2.setText("A");

        txtResultA.setEditable(false);
        jScrollPane11.setViewportView(txtResultA);

        lblComponenteB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB4.setText("B");

        txtResultB.setEditable(false);
        jScrollPane12.setViewportView(txtResultB);

        lblComponenteB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComponenteB5.setText("C");

        txtResultC.setEditable(false);
        jScrollPane13.setViewportView(txtResultC);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(lblMagnitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lblMagnitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblComponenteA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lblComponenteB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblComponenteB2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5)
                                    .addComponent(lblMagnitud2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(lblMagnitud3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblComponenteA1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(lblComponenteB1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblComponenteB3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(btnGraficar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblAngulo2d1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblComponenteA2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblComponenteB4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComponenteB5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMagnitud1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteA)
                            .addComponent(lblComponenteB)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteB2)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMagnitud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMagnitud3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteA1)
                            .addComponent(lblComponenteB1)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComponenteB3)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMagnitud2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAngulo2d1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComponenteA2)
                    .addComponent(lblComponenteB4)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComponenteB5)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnGraficar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        btnRegresar.setText("VOLVER");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnSalir))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Double x1= Double.parseDouble(txtComponenteA1.getText());
        Double y1= Double.parseDouble(txtComponenteB1.getText());
        Double z1 = Double.parseDouble(txtComponenteC1.getText());
        Double x2= Double.parseDouble(txtComponenteA2.getText());
        Double y2= Double.parseDouble(txtComponenteB2.getText());
        Double z2 = Double.parseDouble(txtComponenteC2.getText());
        //MAGNITUD
        txtResult.setText(formato1.format(oper.productoCruz3D(x1, y1, z1, x2, y2, z2, txtResultA, txtResultB, txtResultC)));

        //ANGULO
        txtAngulo.setText(formato1.format(oper.productoCruzAngulo(oper.productoCruz3D(x1,
            y1, z1, x2, y2, z2, txtResultA, txtResultB, txtResultC), oper.calcularMagnitud3D(x1, y1, z1), oper.calcularMagnitud3D(x2, y2, z2))));
        
        //MAGNITUD DE VECTORES 1 Y 2
        txtMagnitud1.setText(formato1.format(oper.calcularMagnitud3D(x1, y1, z1)));
        txtMagnitud2.setText(formato1.format(oper.calcularMagnitud3D(x2, y2, z2)));
        
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtMagnitud1.setText("");
        txtMagnitud2.setText("");
        txtComponenteA1.setText("");
        txtComponenteA2.setText("");
        txtComponenteB1.setText("");
        txtComponenteB2.setText("");
        txtComponenteC1.setText("");
        txtComponenteC2.setText("");
        txtResult.setText("");
        txtAngulo.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Interfaz interfaz = new Interfaz();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        //Establecer puntos para graficar
        grafX1= Double.parseDouble(txtComponenteA1.getText());
        grafX2= Double.parseDouble(txtComponenteA2.getText());
        grafY1= Double.parseDouble(txtComponenteB1.getText());
        grafY2= Double.parseDouble(txtComponenteB2.getText());
        grafZ1= Double.parseDouble(txtComponenteC1.getText());
        grafZ2= Double.parseDouble(txtComponenteC2.getText());
        grafRX= Double.parseDouble(txtResultA.getText());
        grafRY= Double.parseDouble(txtResultB.getText());
        grafRZ= Double.parseDouble(txtResultC.getText());
        //Crear arreglos a graficar
        arrX1= hacerArreglo(x, grafX1);
        arrY1=hacerArreglo(y, grafY1);
        arrZ1=hacerArreglo(z, grafZ1);
        arrX2= hacerArreglo(x, grafX2);
        arrY2=hacerArreglo(y, grafY2);
        arrZ2=hacerArreglo(z, grafZ2);
        arrRX=hacerArreglo(x,grafRX);
        arrRY=hacerArreglo(y,grafRY);
        arrRZ=hacerArreglo(z,grafRZ);
        //GRAFICAR
        Grafica3D graf = new Grafica3D();
        graf.grafica3D.addLinePlot("Vector 1",Color.BLUE,arrX1,arrY1,arrZ1);
        graf.grafica3D.addLinePlot("Vector 2",Color.RED,arrX2,arrY2,arrZ2);
        graf.grafica3D.addLinePlot("Vector Producto Cruz",Color.MAGENTA,arrRX,arrRY,arrRZ);
        graf.espaGrafica.setVisible(true);
    }//GEN-LAST:event_btnGraficarActionPerformed

    public double[] hacerArreglo(double[]arr, double valor){
        double []newA = new double[arr.length];
        
        for(int i=0; i<arr.length;i++){
            newA[i]=arr[i];
        }
        newA[newA.length-1] = valor;
        
        return newA;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoCruz3D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JToggleButton btnGraficar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAngulo2d1;
    private javax.swing.JLabel lblComponenteA;
    private javax.swing.JLabel lblComponenteA1;
    private javax.swing.JLabel lblComponenteA2;
    private javax.swing.JLabel lblComponenteB;
    private javax.swing.JLabel lblComponenteB1;
    private javax.swing.JLabel lblComponenteB2;
    private javax.swing.JLabel lblComponenteB3;
    private javax.swing.JLabel lblComponenteB4;
    private javax.swing.JLabel lblComponenteB5;
    private javax.swing.JLabel lblMagnitud;
    private javax.swing.JLabel lblMagnitud1;
    private javax.swing.JLabel lblMagnitud2;
    private javax.swing.JLabel lblMagnitud3;
    private javax.swing.JTextPane txtAngulo;
    private javax.swing.JTextPane txtComponenteA1;
    private javax.swing.JTextPane txtComponenteA2;
    private javax.swing.JTextPane txtComponenteB1;
    private javax.swing.JTextPane txtComponenteB2;
    private javax.swing.JTextPane txtComponenteC1;
    private javax.swing.JTextPane txtComponenteC2;
    private javax.swing.JTextPane txtMagnitud1;
    private javax.swing.JTextPane txtMagnitud2;
    private javax.swing.JTextPane txtResult;
    private javax.swing.JTextPane txtResultA;
    private javax.swing.JTextPane txtResultB;
    private javax.swing.JTextPane txtResultC;
    // End of variables declaration//GEN-END:variables
}
